export const dashboardMockData = {
  overview: {
    activeDrives: 8,
    totalRegistrations: 426,
    certifiedCount: 293,
    availableVouchers: 74,
    previousActiveDrives: 6,
    previousRegistrations: 388,
    failedCount: 41,
    assignedVouchers: 116,
    redeemedVouchers: 192,
  },
  quickMetrics: {
    issuedThisMonth: 48,
    averageApprovalTime: '6h 20m',
    averageAssessmentScore: 746,
    openRegistrations: 91,
    pendingApprovals: 23,
    slaCompliance: 94,
    expiredVouchers: 5,
    budgetUtilization: 68,
  },
  drives: [
    {
      driveId: 'aws-q3',
      driveName: 'AWS Solutions Architect Associate - Q3 2026',
      vendorName: 'AWS',
      certificationName: 'Solutions Architect Associate',
      status: 'Open',
      registrationCount: 118,
      approvalCount: 91,
      examCompleted: 64,
      passRate: 82,
      voucherUtilization: 76,
      targetAchievement: 79,
      budgetUtilization: 63,
      targetCount: 150,
    },
    {
      driveId: 'azure-q3',
      driveName: 'Azure Fundamentals Enterprise Wave',
      vendorName: 'Microsoft',
      certificationName: 'Azure Fundamentals',
      status: 'Open',
      registrationCount: 96,
      approvalCount: 80,
      examCompleted: 58,
      passRate: 88,
      voucherUtilization: 69,
      targetAchievement: 80,
      budgetUtilization: 54,
      targetCount: 120,
    },
    {
      driveId: 'gcp-q3',
      driveName: 'Google Cloud Digital Leader',
      vendorName: 'Google Cloud',
      certificationName: 'Cloud Digital Leader',
      status: 'Closed',
      registrationCount: 74,
      approvalCount: 70,
      examCompleted: 66,
      passRate: 79,
      voucherUtilization: 92,
      targetAchievement: 93,
      budgetUtilization: 84,
      targetCount: 80,
    },
  ],
  activity: [
    { id: 1, type: 'Registration Approved', user: 'Sanjay Menon', entity: 'AWS Q3 Drive', status: 'Approved', timestamp: '10 min ago' },
    { id: 2, type: 'Voucher Assigned', user: 'Divya Iyer', entity: 'AWS-X7****9', status: 'Assigned', timestamp: '22 min ago' },
    { id: 3, type: 'Assessment Passed', user: 'Arjun Sharma', entity: 'AWS SAA', status: 'Passed', timestamp: '41 min ago' },
    { id: 4, type: 'Registration Submitted', user: 'Priya Nair', entity: 'Azure Fundamentals', status: 'Submitted', timestamp: '1 hr ago' },
  ],
  approvals: [
    { id: 'ap-1', candidate: 'Priya Nair', drive: 'Azure Fundamentals', age: '2 days', type: 'Registration' },
    { id: 'ap-2', candidate: 'Karthik Raman', drive: 'Security Specialty', age: '1 day', type: 'Eligibility' },
    { id: 'ap-3', candidate: 'Meera Reddy', drive: 'GCP Digital Leader', age: '6 hours', type: 'Manual Approval' },
  ],
  sla: {
    compliance: 94,
    breachedCount: 7,
    averageResponseTime: '18m',
    averageApprovalTime: '6h 20m',
  },
  analytics: {
    passRateTrend: [
      { month: 'Jan', passRate: 72 },
      { month: 'Feb', passRate: 76 },
      { month: 'Mar', passRate: 81 },
      { month: 'Apr', passRate: 79 },
      { month: 'May', passRate: 84 },
      { month: 'Jun', passRate: 86 },
    ],
    vendorDistribution: [
      { name: 'AWS', value: 42 },
      { name: 'Microsoft', value: 34 },
      { name: 'Google Cloud', value: 24 },
    ],
    monthlyCertifications: [
      { month: 'Apr', count: 38 },
      { month: 'May', count: 44 },
      { month: 'Jun', count: 48 },
    ],
  },
  alerts: [
    { id: 'al-1', severity: 'Critical', title: 'SLA breach risk', message: '7 approvals are outside the target response window.' },
    { id: 'al-2', severity: 'High', title: 'Voucher expiry risk', message: '5 vouchers expire within 14 days.' },
    { id: 'al-3', severity: 'Medium', title: 'Budget threshold reached', message: 'GCP drive has consumed 84% of allocated budget.' },
  ],
};
