export const mockDrives = [
  {
    driveId: 'aws-saa-q3-2026',
    driveName: 'AWS Solutions Architect Associate - Q3 2026',
    driveCode: 'AWS-SAA-Q3-2026',
    vendorName: 'AWS',
    certificationName: 'Solutions Architect Associate',
    certificationLevel: 'Associate',
    sponsorName: 'Cloud Center of Excellence',
    businessUnit: 'BFSI',
    owner: 'Priya Nair',
    status: 'Active',
    description: 'Enterprise certification wave for cloud architects.',
    objectives: 'Improve solution design capability across delivery teams.',
    registrationStartDate: '2026-07-01',
    registrationEndDate: '2026-07-20',
    examWindowStartDate: '2026-08-01',
    examWindowEndDate: '2026-09-15',
    closureDate: '2026-09-30',
    targetCount: 150,
    currentRegistrationCount: 118,
    approvedCount: 91,
    examTakenCount: 64,
    passedCount: 52,
    failedCount: 12,
    voucherAssignedCount: 82,
    voucherRedeemedCount: 48,
    budgetAllocated: 3750000,
    budgetConsumed: 2360000,
    passRate: 82,
    voucherUtilization: 76,
    managerApprovalRequired: true,
    attemptLimit: 2,
    tenureRequiredDays: 180,
    trainingCompletionRequired: true,
    createdDate: '2026-06-10',
  },
  {
    driveId: 'azure-fundamentals-2026',
    driveName: 'Azure Fundamentals Enterprise Wave',
    driveCode: 'AZ-900-ENT-2026',
    vendorName: 'Azure',
    certificationName: 'Azure Fundamentals',
    certificationLevel: 'Fundamentals',
    sponsorName: 'Platform Engineering',
    businessUnit: 'Retail',
    owner: 'Arjun Sharma',
    status: 'Draft',
    description: 'Foundational Azure certification for engineering teams.',
    objectives: 'Build common cloud vocabulary and readiness.',
    registrationStartDate: '2026-08-01',
    registrationEndDate: '2026-08-18',
    examWindowStartDate: '2026-09-01',
    examWindowEndDate: '2026-09-30',
    closureDate: '2026-10-10',
    targetCount: 120,
    currentRegistrationCount: 0,
    approvedCount: 0,
    examTakenCount: 0,
    passedCount: 0,
    failedCount: 0,
    voucherAssignedCount: 0,
    voucherRedeemedCount: 0,
    budgetAllocated: 1200000,
    budgetConsumed: 0,
    passRate: 0,
    voucherUtilization: 0,
    managerApprovalRequired: false,
    attemptLimit: 1,
    tenureRequiredDays: 90,
    trainingCompletionRequired: true,
    createdDate: '2026-06-08',
  },
  {
    driveId: 'gcp-digital-leader-q2',
    driveName: 'Google Cloud Digital Leader - Q2 Closeout',
    driveCode: 'GCP-CDL-Q2-2026',
    vendorName: 'Google Cloud',
    certificationName: 'Cloud Digital Leader',
    certificationLevel: 'Foundational',
    sponsorName: 'Data Engineering',
    businessUnit: 'Healthcare',
    owner: 'Divya Iyer',
    status: 'Closed',
    description: 'Digital leader certification drive for analytics teams.',
    objectives: 'Increase cloud literacy for data modernization programs.',
    registrationStartDate: '2026-04-01',
    registrationEndDate: '2026-04-22',
    examWindowStartDate: '2026-05-01',
    examWindowEndDate: '2026-06-10',
    closureDate: '2026-06-20',
    targetCount: 80,
    currentRegistrationCount: 74,
    approvedCount: 70,
    examTakenCount: 66,
    passedCount: 52,
    failedCount: 14,
    voucherAssignedCount: 70,
    voucherRedeemedCount: 66,
    budgetAllocated: 960000,
    budgetConsumed: 806000,
    passRate: 79,
    voucherUtilization: 92,
    managerApprovalRequired: true,
    attemptLimit: 2,
    tenureRequiredDays: 120,
    trainingCompletionRequired: false,
    createdDate: '2026-03-25',
  },
];

export const mockDriveRegistrations = [
  { id: 'reg-1', employee: 'Sanjay Menon', department: 'Cloud', manager: 'priya.nair@maverick.com', registrationDate: '2026-07-02', status: 'Approved', eligibility: 'Passed', assessment: 'Pending', voucher: 'Assigned', certification: 'In Progress' },
  { id: 'reg-2', employee: 'Ananya Krishnan', department: 'Security', manager: 'rohit.verma@maverick.com', registrationDate: '2026-07-03', status: 'Pending Approval', eligibility: 'Review', assessment: 'Not Started', voucher: 'Not Assigned', certification: 'Not Started' },
  { id: 'reg-3', employee: 'Vivek Kumar', department: 'Platform Engineering', manager: 'divya.iyer@maverick.com', registrationDate: '2026-07-04', status: 'Approved', eligibility: 'Passed', assessment: 'Passed', voucher: 'Redeemed', certification: 'Certified' },
];

export const mockDriveVouchers = [
  { id: 'v-1', maskedCode: 'AWS-X7****9', assignedUser: 'Sanjay Menon', status: 'Assigned', assignedDate: '2026-07-12', redeemedDate: '', expiryDate: '2026-10-31' },
  { id: 'v-2', maskedCode: 'AWS-P4****2', assignedUser: 'Vivek Kumar', status: 'Redeemed', assignedDate: '2026-07-10', redeemedDate: '2026-08-12', expiryDate: '2026-10-31' },
  { id: 'v-3', maskedCode: 'AWS-L2****5', assignedUser: '', status: 'Available', assignedDate: '', redeemedDate: '', expiryDate: '2026-10-31' },
];

export const mockDriveAnalytics = {
  registrationTrend: [
    { date: 'Jul 1', registrations: 18 },
    { date: 'Jul 5', registrations: 47 },
    { date: 'Jul 10', registrations: 82 },
    { date: 'Jul 15', registrations: 118 },
  ],
  passRateTrend: [
    { date: 'Aug 1', passRate: 74 },
    { date: 'Aug 15', passRate: 80 },
    { date: 'Sep 1', passRate: 82 },
  ],
  departmentPerformance: [
    { department: 'Cloud', passed: 22, failed: 4 },
    { department: 'Data Engineering', passed: 14, failed: 3 },
    { department: 'Security', passed: 9, failed: 3 },
  ],
  voucherUtilization: [
    { name: 'Available', value: 34 },
    { name: 'Assigned', value: 82 },
    { name: 'Redeemed', value: 48 },
  ],
};

export const mockDriveAudit = [
  { id: 'a-1', who: 'Priya Nair', what: 'Drive created', when: '2026-06-10 09:30', before: '{}', after: '{"status":"Draft"}' },
  { id: 'a-2', who: 'Priya Nair', what: 'Drive activated', when: '2026-06-18 10:15', before: '{"status":"Draft"}', after: '{"status":"Active"}' },
  { id: 'a-3', who: 'System', what: 'Voucher pool imported', when: '2026-07-01 18:20', before: '{"vouchers":0}', after: '{"vouchers":120}' },
];
