// <auto-generated />
using System;
using CertificationHub.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CertificationHub.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260610121237_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CertificationHub.Domain.Entities.AssessmentResult", b =>
                {
                    b.Property<Guid>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmittedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("ResultId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Outcome");

                    b.HasIndex("RegistrationId")
                        .IsUnique();

                    b.ToTable("AssessmentResults", (string)null);
                });

            modelBuilder.Entity("CertificationHub.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("AfterSnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BeforeSnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DriveId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("AuditLogId");

                    b.HasIndex("ActorId");

                    b.HasIndex("DriveId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("EntityName", "EntityId");

                    b.ToTable("AuditLogs", (string)null);

                    b.HasData(
                        new
                        {
                            AuditLogId = new Guid("70000000-0000-0000-0000-000000000001"),
                            Action = "Created",
                            ActorId = new Guid("10000000-0000-0000-0000-000000000001"),
                            ActorName = "Maverick Administrator",
                            AfterSnapshotJson = "{\"status\":\"Open\"}",
                            BeforeSnapshotJson = "{}",
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DriveId = new Guid("20000000-0000-0000-0000-000000000001"),
                            EntityId = "20000000-0000-0000-0000-000000000001",
                            EntityName = "CertificationDrive",
                            IPAddress = "127.0.0.1",
                            ModifiedBy = "",
                            RowVersion = new byte[0],
                            Timestamp = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserAgent = "SeedData/1.0"
                        },
                        new
                        {
                            AuditLogId = new Guid("70000000-0000-0000-0000-000000000002"),
                            Action = "Approved",
                            ActorId = new Guid("10000000-0000-0000-0000-000000000001"),
                            ActorName = "Maverick Administrator",
                            AfterSnapshotJson = "{\"status\":\"Approved\"}",
                            BeforeSnapshotJson = "{\"status\":\"Pending\"}",
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DriveId = new Guid("20000000-0000-0000-0000-000000000001"),
                            EntityId = "40000000-0000-0000-0000-000000000001",
                            EntityName = "Registration",
                            IPAddress = "127.0.0.1",
                            ModifiedBy = "",
                            RowVersion = new byte[0],
                            Timestamp = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserAgent = "SeedData/1.0"
                        },
                        new
                        {
                            AuditLogId = new Guid("70000000-0000-0000-0000-000000000003"),
                            Action = "Assigned",
                            ActorId = new Guid("10000000-0000-0000-0000-000000000001"),
                            ActorName = "Maverick Administrator",
                            AfterSnapshotJson = "{\"status\":\"Assigned\"}",
                            BeforeSnapshotJson = "{\"status\":\"Available\"}",
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DriveId = new Guid("20000000-0000-0000-0000-000000000001"),
                            EntityId = "50000000-0000-0000-0000-000000000001",
                            EntityName = "Voucher",
                            IPAddress = "127.0.0.1",
                            ModifiedBy = "",
                            RowVersion = new byte[0],
                            Timestamp = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserAgent = "SeedData/1.0"
                        });
                });

            modelBuilder.Entity("CertificationHub.Domain.Entities.CertificationDrive", b =>
                {
                    b.Property<Guid>("DriveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptLimit")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BudgetAllocated")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BudgetConsumed")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CertificationName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentCertifiedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentRegistrationCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeletedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriveCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DriveName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExamWindowEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExamWindowStartDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ManagerApprovalRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PolicyUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegistrationEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegistrationStartDate")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("SponsorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TenureRequiredDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("DriveId");

                    b.HasIndex("DriveCode")
                        .IsUnique();

                    b.HasIndex("IsDeleted");

                    b.HasIndex("RegistrationStartDate");

                    b.HasIndex("Status");

                    b.HasIndex("VendorName");

                    b.ToTable("CertificationDrives", (string)null);

                    b.HasData(
                        new
                        {
                            DriveId = new Guid("20000000-0000-0000-0000-000000000001"),
                            AttemptLimit = 2,
                            BudgetAllocated = 500000m,
                            BudgetConsumed = 65000m,
                            CertificationName = "AWS Certified Solutions Architect - Associate",
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentCertifiedCount = 1,
                            CurrentRegistrationCount = 5,
                            DeletedBy = "",
                            DriveCode = "AWS-SAA-Q3-2026",
                            DriveName = "AWS Solutions Architect Associate - Q3 2026",
                            ExamWindowEndDate = new DateTime(2026, 9, 30, 23, 59, 59, 0, DateTimeKind.Utc),
                            ExamWindowStartDate = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            ManagerApprovalRequired = true,
                            ModifiedBy = "",
                            PolicyUrl = "https://maverick.example.com/policies/aws-saa-q3-2026",
                            RegistrationEndDate = new DateTime(2026, 7, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            RegistrationStartDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RowVersion = new byte[0],
                            SponsorName = "Cloud Center of Excellence",
                            Status = "Open",
                            TargetCount = 50,
                            TenureRequiredDays = 180,
                            VendorName = "AWS"
                        });
                });

            modelBuilder.Entity("CertificationHub.Domain.Entities.EligibilityRecord", b =>
                {
                    b.Property<Guid>("EligibilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApproverId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriteriaJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DecisionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionReason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEligible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("EligibilityId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("RegistrationId")
                        .IsUnique();

                    b.ToTable("EligibilityRecords", (string)null);
                });

            modelBuilder.Entity("CertificationHub.Domain.Entities.EmployeeCertification", b =>
                {
                    b.Property<Guid>("CertificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificationName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("IssuedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("CertificationId");

                    b.HasIndex("CertificationName");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("UserId");

                    b.ToTable("EmployeeCertifications", (string)null);

                    b.HasData(
                        new
                        {
                            CertificationId = new Guid("30000000-0000-0000-0000-000000000001"),
                            CertificationName = "AWS Cloud Practitioner",
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            CredentialId = "AWS-CP-2025-101",
                            DeletedBy = "",
                            ExpiryDate = new DateTime(2028, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsExpired = false,
                            IssuedDate = new DateTime(2025, 8, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "",
                            RowVersion = new byte[0],
                            UserId = new Guid("10000000-0000-0000-0000-000000000101"),
                            VendorName = "AWS"
                        },
                        new
                        {
                            CertificationId = new Guid("30000000-0000-0000-0000-000000000002"),
                            CertificationName = "Azure Fundamentals",
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            CredentialId = "AZ-900-2025-102",
                            DeletedBy = "",
                            ExpiryDate = new DateTime(2028, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsExpired = false,
                            IssuedDate = new DateTime(2025, 10, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "",
                            RowVersion = new byte[0],
                            UserId = new Guid("10000000-0000-0000-0000-000000000102"),
                            VendorName = "Microsoft"
                        },
                        new
                        {
                            CertificationId = new Guid("30000000-0000-0000-0000-000000000003"),
                            CertificationName = "Google Cloud Digital Leader",
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            CredentialId = "GCDL-2025-103",
                            DeletedBy = "",
                            ExpiryDate = new DateTime(2028, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsExpired = false,
                            IssuedDate = new DateTime(2025, 12, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "",
                            RowVersion = new byte[0],
                            UserId = new Guid("10000000-0000-0000-0000-000000000103"),
                            VendorName = "Google Cloud"
                        },
                        new
                        {
                            CertificationId = new Guid("30000000-0000-0000-0000-000000000004"),
                            CertificationName = "AWS Cloud Practitioner",
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            CredentialId = "AWS-CP-2025-104",
                            DeletedBy = "",
                            ExpiryDate = new DateTime(2028, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsExpired = false,
                            IssuedDate = new DateTime(2026, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "",
                            RowVersion = new byte[0],
                            UserId = new Guid("10000000-0000-0000-0000-000000000104"),
                            VendorName = "AWS"
                        },
                        new
                        {
                            CertificationId = new Guid("30000000-0000-0000-0000-000000000005"),
                            CertificationName = "Azure Fundamentals",
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            CredentialId = "AZ-900-2025-105",
                            DeletedBy = "",
                            ExpiryDate = new DateTime(2028, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            IsExpired = false,
                            IssuedDate = new DateTime(2026, 2, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            ModifiedBy = "",
                            RowVersion = new byte[0],
                            UserId = new Guid("10000000-0000-0000-0000-000000000105"),
                            VendorName = "Microsoft"
                        });
                });

            modelBuilder.Entity("CertificationHub.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReadDate")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("SLAStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("NotificationId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("IsRead");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications", (string)null);

                    b.HasData(
                        new
                        {
                            NotificationId = new Guid("60000000-0000-0000-0000-000000000001"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedBy = "",
                            IsDeleted = false,
                            IsRead = false,
                            Message = "Registration approved for AWS Solutions Architect Associate - Q3 2026.",
                            ModifiedBy = "",
                            RowVersion = new byte[0],
                            SLAStatus = "OnTrack",
                            Type = "RegistrationUpdate",
                            UserId = new Guid("10000000-0000-0000-0000-000000000101")
                        },
                        new
                        {
                            NotificationId = new Guid("60000000-0000-0000-0000-000000000002"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedBy = "",
                            IsDeleted = false,
                            IsRead = false,
                            Message = "Voucher assigned for your AWS certification exam.",
                            ModifiedBy = "",
                            RowVersion = new byte[0],
                            SLAStatus = "OnTrack",
                            Type = "VoucherAssigned",
                            UserId = new Guid("10000000-0000-0000-0000-000000000104")
                        },
                        new
                        {
                            NotificationId = new Guid("60000000-0000-0000-0000-000000000003"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedBy = "",
                            IsDeleted = false,
                            IsRead = false,
                            Message = "Exam reminder: complete your certification assessment evidence upload.",
                            ModifiedBy = "",
                            RowVersion = new byte[0],
                            SLAStatus = "OnTrack",
                            Type = "AssessmentResult",
                            UserId = new Guid("10000000-0000-0000-0000-000000000105")
                        });
                });

            modelBuilder.Entity("CertificationHub.Domain.Entities.Registration", b =>
                {
                    b.Property<Guid>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovalComments")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ApproverId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DriveId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExamTrack")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredSlot")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("PriorAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("RegistrationId");

                    b.HasIndex("DriveId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "DriveId")
                        .IsUnique();

                    b.ToTable("Registrations", (string)null);

                    b.HasData(
                        new
                        {
                            RegistrationId = new Guid("40000000-0000-0000-0000-000000000001"),
                            ApprovalComments = "Approved for cloud role alignment.",
                            ApprovalDate = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            ApproverId = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedBy = "",
                            DriveId = new Guid("20000000-0000-0000-0000-000000000001"),
                            ExamTrack = "Associate",
                            IsDeleted = false,
                            ModifiedBy = "",
                            PreferredSlot = "Weekday Morning",
                            PriorAttempts = 0,
                            RegisteredDate = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            RowVersion = new byte[0],
                            Status = "Approved",
                            UserId = new Guid("10000000-0000-0000-0000-000000000101")
                        },
                        new
                        {
                            RegistrationId = new Guid("40000000-0000-0000-0000-000000000002"),
                            ApprovalComments = "",
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedBy = "",
                            DriveId = new Guid("20000000-0000-0000-0000-000000000001"),
                            ExamTrack = "Associate",
                            IsDeleted = false,
                            ModifiedBy = "",
                            PreferredSlot = "Weekday Morning",
                            PriorAttempts = 0,
                            RegisteredDate = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            RowVersion = new byte[0],
                            Status = "Pending",
                            UserId = new Guid("10000000-0000-0000-0000-000000000102")
                        },
                        new
                        {
                            RegistrationId = new Guid("40000000-0000-0000-0000-000000000003"),
                            ApprovalComments = "Prerequisite certification not completed.",
                            ApprovalDate = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            ApproverId = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedBy = "",
                            DriveId = new Guid("20000000-0000-0000-0000-000000000001"),
                            ExamTrack = "Associate",
                            IsDeleted = false,
                            ModifiedBy = "",
                            PreferredSlot = "Weekday Morning",
                            PriorAttempts = 0,
                            RegisteredDate = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            RowVersion = new byte[0],
                            Status = "Rejected",
                            UserId = new Guid("10000000-0000-0000-0000-000000000103")
                        },
                        new
                        {
                            RegistrationId = new Guid("40000000-0000-0000-0000-000000000004"),
                            ApprovalComments = "Voucher assigned.",
                            ApprovalDate = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            ApproverId = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedBy = "",
                            DriveId = new Guid("20000000-0000-0000-0000-000000000001"),
                            ExamTrack = "Associate",
                            IsDeleted = false,
                            ModifiedBy = "",
                            PreferredSlot = "Weekday Morning",
                            PriorAttempts = 0,
                            RegisteredDate = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            RowVersion = new byte[0],
                            Status = "Approved",
                            UserId = new Guid("10000000-0000-0000-0000-000000000104")
                        },
                        new
                        {
                            RegistrationId = new Guid("40000000-0000-0000-0000-000000000005"),
                            ApprovalComments = "Certified after assessment submission.",
                            ApprovalDate = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            ApproverId = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedBy = "",
                            DriveId = new Guid("20000000-0000-0000-0000-000000000001"),
                            ExamTrack = "Associate",
                            IsDeleted = false,
                            ModifiedBy = "",
                            PreferredSlot = "Weekday Morning",
                            PriorAttempts = 0,
                            RegisteredDate = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            RowVersion = new byte[0],
                            Status = "Completed",
                            UserId = new Guid("10000000-0000-0000-0000-000000000105")
                        });
                });

            modelBuilder.Entity("CertificationHub.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessUnit")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastLoginDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("ManagerEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Role");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("10000000-0000-0000-0000-000000000001"),
                            BusinessUnit = "BFSI",
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedBy = "",
                            Department = "Platform Engineering",
                            Email = "admin@maverick.com",
                            EmployeeId = "MAV-ADMIN-001",
                            FullName = "Maverick Administrator",
                            IsActive = true,
                            IsDeleted = false,
                            LastLoginDate = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Bengaluru",
                            ManagerEmail = "cio@maverick.com",
                            ModifiedBy = "",
                            PasswordHash = "$2a$11$ZONQLjnpJocHuJeJaJGcEuhwh1kLPJKb1ZC9klf6Vw.KAX1MTW2Gq",
                            Role = "Admin",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            UserId = new Guid("10000000-0000-0000-0000-000000000101"),
                            BusinessUnit = "BFSI",
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedBy = "",
                            Department = "Cloud",
                            Email = "arjun.sharma@maverick.com",
                            EmployeeId = "MAV-EMP-101",
                            FullName = "Arjun Sharma",
                            IsActive = true,
                            IsDeleted = false,
                            LastLoginDate = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Bengaluru",
                            ManagerEmail = "manager.cloud@maverick.com",
                            ModifiedBy = "",
                            PasswordHash = "$2a$11$ZONQLjnpJocHuJeJaJGcEuhwh1kLPJKb1ZC9klf6Vw.KAX1MTW2Gq",
                            Role = "Employee",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            UserId = new Guid("10000000-0000-0000-0000-000000000102"),
                            BusinessUnit = "Retail",
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedBy = "",
                            Department = "Data Engineering",
                            Email = "priya.nair@maverick.com",
                            EmployeeId = "MAV-EMP-102",
                            FullName = "Priya Nair",
                            IsActive = true,
                            IsDeleted = false,
                            LastLoginDate = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Kochi",
                            ManagerEmail = "manager.data@maverick.com",
                            ModifiedBy = "",
                            PasswordHash = "$2a$11$ZONQLjnpJocHuJeJaJGcEuhwh1kLPJKb1ZC9klf6Vw.KAX1MTW2Gq",
                            Role = "Employee",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            UserId = new Guid("10000000-0000-0000-0000-000000000103"),
                            BusinessUnit = "Healthcare",
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedBy = "",
                            Department = "Security",
                            Email = "karthik.raman@maverick.com",
                            EmployeeId = "MAV-EMP-103",
                            FullName = "Karthik Raman",
                            IsActive = true,
                            IsDeleted = false,
                            LastLoginDate = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Chennai",
                            ManagerEmail = "manager.security@maverick.com",
                            ModifiedBy = "",
                            PasswordHash = "$2a$11$ZONQLjnpJocHuJeJaJGcEuhwh1kLPJKb1ZC9klf6Vw.KAX1MTW2Gq",
                            Role = "Employee",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            UserId = new Guid("10000000-0000-0000-0000-000000000104"),
                            BusinessUnit = "BFSI",
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedBy = "",
                            Department = "Platform Engineering",
                            Email = "divya.iyer@maverick.com",
                            EmployeeId = "MAV-EMP-104",
                            FullName = "Divya Iyer",
                            IsActive = true,
                            IsDeleted = false,
                            LastLoginDate = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Pune",
                            ManagerEmail = "manager.platform@maverick.com",
                            ModifiedBy = "",
                            PasswordHash = "$2a$11$ZONQLjnpJocHuJeJaJGcEuhwh1kLPJKb1ZC9klf6Vw.KAX1MTW2Gq",
                            Role = "Employee",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            UserId = new Guid("10000000-0000-0000-0000-000000000105"),
                            BusinessUnit = "Retail",
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedBy = "",
                            Department = "Cloud",
                            Email = "rohit.verma@maverick.com",
                            EmployeeId = "MAV-EMP-105",
                            FullName = "Rohit Verma",
                            IsActive = true,
                            IsDeleted = false,
                            LastLoginDate = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Hyderabad",
                            ManagerEmail = "manager.cloud@maverick.com",
                            ModifiedBy = "",
                            PasswordHash = "$2a$11$ZONQLjnpJocHuJeJaJGcEuhwh1kLPJKb1ZC9klf6Vw.KAX1MTW2Gq",
                            Role = "Employee",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            UserId = new Guid("10000000-0000-0000-0000-000000000106"),
                            BusinessUnit = "Healthcare",
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedBy = "",
                            Department = "Data Engineering",
                            Email = "neha.gupta@maverick.com",
                            EmployeeId = "MAV-EMP-106",
                            FullName = "Neha Gupta",
                            IsActive = true,
                            IsDeleted = false,
                            LastLoginDate = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Gurugram",
                            ManagerEmail = "manager.data@maverick.com",
                            ModifiedBy = "",
                            PasswordHash = "$2a$11$ZONQLjnpJocHuJeJaJGcEuhwh1kLPJKb1ZC9klf6Vw.KAX1MTW2Gq",
                            Role = "Employee",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            UserId = new Guid("10000000-0000-0000-0000-000000000107"),
                            BusinessUnit = "BFSI",
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedBy = "",
                            Department = "Security",
                            Email = "sanjay.menon@maverick.com",
                            EmployeeId = "MAV-EMP-107",
                            FullName = "Sanjay Menon",
                            IsActive = true,
                            IsDeleted = false,
                            LastLoginDate = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Mumbai",
                            ManagerEmail = "manager.security@maverick.com",
                            ModifiedBy = "",
                            PasswordHash = "$2a$11$ZONQLjnpJocHuJeJaJGcEuhwh1kLPJKb1ZC9klf6Vw.KAX1MTW2Gq",
                            Role = "Manager",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            UserId = new Guid("10000000-0000-0000-0000-000000000108"),
                            BusinessUnit = "Retail",
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedBy = "",
                            Department = "Platform Engineering",
                            Email = "ananya.krishnan@maverick.com",
                            EmployeeId = "MAV-EMP-108",
                            FullName = "Ananya Krishnan",
                            IsActive = true,
                            IsDeleted = false,
                            LastLoginDate = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Coimbatore",
                            ManagerEmail = "manager.platform@maverick.com",
                            ModifiedBy = "",
                            PasswordHash = "$2a$11$ZONQLjnpJocHuJeJaJGcEuhwh1kLPJKb1ZC9klf6Vw.KAX1MTW2Gq",
                            Role = "Employee",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            UserId = new Guid("10000000-0000-0000-0000-000000000109"),
                            BusinessUnit = "Healthcare",
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedBy = "",
                            Department = "Cloud",
                            Email = "vivek.kumar@maverick.com",
                            EmployeeId = "MAV-EMP-109",
                            FullName = "Vivek Kumar",
                            IsActive = true,
                            IsDeleted = false,
                            LastLoginDate = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Noida",
                            ManagerEmail = "manager.cloud@maverick.com",
                            ModifiedBy = "",
                            PasswordHash = "$2a$11$ZONQLjnpJocHuJeJaJGcEuhwh1kLPJKb1ZC9klf6Vw.KAX1MTW2Gq",
                            Role = "Employee",
                            RowVersion = new byte[0]
                        },
                        new
                        {
                            UserId = new Guid("10000000-0000-0000-0000-000000000110"),
                            BusinessUnit = "BFSI",
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedBy = "",
                            Department = "Data Engineering",
                            Email = "meera.reddy@maverick.com",
                            EmployeeId = "MAV-EMP-110",
                            FullName = "Meera Reddy",
                            IsActive = true,
                            IsDeleted = false,
                            LastLoginDate = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Bengaluru",
                            ManagerEmail = "manager.data@maverick.com",
                            ModifiedBy = "",
                            PasswordHash = "$2a$11$ZONQLjnpJocHuJeJaJGcEuhwh1kLPJKb1ZC9klf6Vw.KAX1MTW2Gq",
                            Role = "Employee",
                            RowVersion = new byte[0]
                        });
                });

            modelBuilder.Entity("CertificationHub.Domain.Entities.Voucher", b =>
                {
                    b.Property<Guid>("VoucherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AssignedDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DriveId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaskedCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RedeemedDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RegistrationId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenizedLink")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("VoucherId");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("DriveId");

                    b.HasIndex("EncryptedCode")
                        .IsUnique();

                    b.HasIndex("IsDeleted");

                    b.HasIndex("RegistrationId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Vouchers", (string)null);

                    b.HasData(
                        new
                        {
                            VoucherId = new Guid("50000000-0000-0000-0000-000000000001"),
                            AssignedDate = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            AssignedToUserId = new Guid("10000000-0000-0000-0000-000000000101"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedBy = "",
                            DriveId = new Guid("20000000-0000-0000-0000-000000000001"),
                            EncryptedCode = "03F6F839DA80A71B88E7E86D1C63130D2E306128644A0372F387AEF85565C848",
                            IsDeleted = false,
                            IsRead = false,
                            MaskedCode = "AWS-****M9",
                            ModifiedBy = "",
                            RegistrationId = new Guid("40000000-0000-0000-0000-000000000001"),
                            Status = "Assigned",
                            TokenizedLink = "https://maverick.example.com/vouchers/1",
                            Value = 15000m,
                            Vendor = "AWS"
                        },
                        new
                        {
                            VoucherId = new Guid("50000000-0000-0000-0000-000000000002"),
                            AssignedDate = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            AssignedToUserId = new Guid("10000000-0000-0000-0000-000000000104"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedBy = "",
                            DeliveryDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DriveId = new Guid("20000000-0000-0000-0000-000000000001"),
                            EncryptedCode = "4FD8657BA5D3B7B59CDB8245D0D50BC87276D2C68C0799D269ED04A53554C89D",
                            IsDeleted = false,
                            IsRead = false,
                            MaskedCode = "AWS-****Q2",
                            ModifiedBy = "",
                            RegistrationId = new Guid("40000000-0000-0000-0000-000000000004"),
                            Status = "Delivered",
                            TokenizedLink = "https://maverick.example.com/vouchers/2",
                            Value = 15000m,
                            Vendor = "AWS"
                        },
                        new
                        {
                            VoucherId = new Guid("50000000-0000-0000-0000-000000000003"),
                            AssignedDate = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            AssignedToUserId = new Guid("10000000-0000-0000-0000-000000000105"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedBy = "",
                            DeliveryDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DriveId = new Guid("20000000-0000-0000-0000-000000000001"),
                            EncryptedCode = "2178EDC879D5701F803790DCDDF0C7EFCFA4D487459B75D63EAFD0A2BBBBBD19",
                            IsDeleted = false,
                            IsRead = true,
                            MaskedCode = "AWS-****R5",
                            ModifiedBy = "",
                            RedeemedDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            RegistrationId = new Guid("40000000-0000-0000-0000-000000000005"),
                            Status = "Redeemed",
                            TokenizedLink = "https://maverick.example.com/vouchers/3",
                            Value = 15000m,
                            Vendor = "AWS"
                        },
                        new
                        {
                            VoucherId = new Guid("50000000-0000-0000-0000-000000000004"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedBy = "",
                            DriveId = new Guid("20000000-0000-0000-0000-000000000001"),
                            EncryptedCode = "1B9E507DEDDE74C8C58E48A540306E37BE3ABE1852BC54D978CF3E0C0908F90E",
                            IsDeleted = false,
                            IsRead = false,
                            MaskedCode = "AWS-****D1",
                            ModifiedBy = "",
                            Status = "Available",
                            TokenizedLink = "",
                            Value = 15000m,
                            Vendor = "AWS"
                        },
                        new
                        {
                            VoucherId = new Guid("50000000-0000-0000-0000-000000000005"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedBy = "",
                            DriveId = new Guid("20000000-0000-0000-0000-000000000001"),
                            EncryptedCode = "60C31C641EA10E0C8F4429F8C088D4EEE15E2404C7843A94D754A86BB3C07750",
                            IsDeleted = false,
                            IsRead = false,
                            MaskedCode = "AWS-****K2",
                            ModifiedBy = "",
                            Status = "Available",
                            TokenizedLink = "",
                            Value = 15000m,
                            Vendor = "AWS"
                        },
                        new
                        {
                            VoucherId = new Guid("50000000-0000-0000-0000-000000000006"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedBy = "",
                            DriveId = new Guid("20000000-0000-0000-0000-000000000001"),
                            EncryptedCode = "16BD663F257BE9F119EB6C7DF6AD9C71C3CC93A2E22D0C8CF182FFA9D280436A",
                            IsDeleted = false,
                            IsRead = false,
                            MaskedCode = "AWS-****P7",
                            ModifiedBy = "",
                            Status = "Available",
                            TokenizedLink = "",
                            Value = 15000m,
                            Vendor = "AWS"
                        },
                        new
                        {
                            VoucherId = new Guid("50000000-0000-0000-0000-000000000007"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedBy = "",
                            DriveId = new Guid("20000000-0000-0000-0000-000000000001"),
                            EncryptedCode = "DF0FCB17522CE66C4D09940CCBA2714E570456263706F7EA4010E9C933C2D2D3",
                            IsDeleted = false,
                            IsRead = false,
                            MaskedCode = "AWS-****S4",
                            ModifiedBy = "",
                            Status = "Available",
                            TokenizedLink = "",
                            Value = 15000m,
                            Vendor = "AWS"
                        },
                        new
                        {
                            VoucherId = new Guid("50000000-0000-0000-0000-000000000008"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedBy = "",
                            DriveId = new Guid("20000000-0000-0000-0000-000000000001"),
                            EncryptedCode = "1F376D8F2980DCCCE9AD030B7E9AA1390B235CA4EFA804E90B23FEFF4C9009F9",
                            IsDeleted = false,
                            IsRead = false,
                            MaskedCode = "AWS-****V3",
                            ModifiedBy = "",
                            Status = "Available",
                            TokenizedLink = "",
                            Value = 15000m,
                            Vendor = "AWS"
                        },
                        new
                        {
                            VoucherId = new Guid("50000000-0000-0000-0000-000000000009"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedBy = "",
                            DriveId = new Guid("20000000-0000-0000-0000-000000000001"),
                            EncryptedCode = "5AA37CDF937F1817B32C47F2AAEE0A695CA8DF83EE387EEBEEEEC478F96C30FC",
                            IsDeleted = false,
                            IsRead = false,
                            MaskedCode = "AWS-****Y9",
                            ModifiedBy = "",
                            Status = "Available",
                            TokenizedLink = "",
                            Value = 15000m,
                            Vendor = "AWS"
                        },
                        new
                        {
                            VoucherId = new Guid("50000000-0000-0000-0000-000000000010"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedBy = "",
                            DriveId = new Guid("20000000-0000-0000-0000-000000000001"),
                            EncryptedCode = "C00940D65A41C8513D1ABB2A666BBAC0E8EF04AEC0C98F5854E666E40D0307DE",
                            IsDeleted = false,
                            IsRead = false,
                            MaskedCode = "AWS-****B8",
                            ModifiedBy = "",
                            Status = "Available",
                            TokenizedLink = "",
                            Value = 15000m,
                            Vendor = "AWS"
                        },
                        new
                        {
                            VoucherId = new Guid("50000000-0000-0000-0000-000000000011"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedBy = "",
                            DriveId = new Guid("20000000-0000-0000-0000-000000000001"),
                            EncryptedCode = "5B906A239C14A46E34110B08E15106DAB9ACAC64306AE51F689B66FB1E91BE24",
                            IsDeleted = false,
                            IsRead = false,
                            MaskedCode = "AWS-****E5",
                            ModifiedBy = "",
                            Status = "Available",
                            TokenizedLink = "",
                            Value = 15000m,
                            Vendor = "AWS"
                        },
                        new
                        {
                            VoucherId = new Guid("50000000-0000-0000-0000-000000000012"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedBy = "",
                            DriveId = new Guid("20000000-0000-0000-0000-000000000001"),
                            EncryptedCode = "6DD07185D344E641497AA94267122CEBFD6475C0732C0E1D54ABABBA2B535A40",
                            IsDeleted = false,
                            IsRead = false,
                            MaskedCode = "AWS-****H1",
                            ModifiedBy = "",
                            Status = "Available",
                            TokenizedLink = "",
                            Value = 15000m,
                            Vendor = "AWS"
                        },
                        new
                        {
                            VoucherId = new Guid("50000000-0000-0000-0000-000000000013"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedBy = "",
                            DriveId = new Guid("20000000-0000-0000-0000-000000000001"),
                            EncryptedCode = "077CF533DCCD875740A9F6A876D2B19FA32AA60CFBA535C96AAB10B3A2E4C5B2",
                            IsDeleted = false,
                            IsRead = false,
                            MaskedCode = "AWS-****L4",
                            ModifiedBy = "",
                            Status = "Available",
                            TokenizedLink = "",
                            Value = 15000m,
                            Vendor = "AWS"
                        },
                        new
                        {
                            VoucherId = new Guid("50000000-0000-0000-0000-000000000014"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedBy = "",
                            DriveId = new Guid("20000000-0000-0000-0000-000000000001"),
                            EncryptedCode = "3D63753D7FAE422D8BFBC39711C263E53415053A01132B6EC1A2FA06B1D37732",
                            IsDeleted = false,
                            IsRead = false,
                            MaskedCode = "AWS-****Q3",
                            ModifiedBy = "",
                            Status = "Available",
                            TokenizedLink = "",
                            Value = 15000m,
                            Vendor = "AWS"
                        },
                        new
                        {
                            VoucherId = new Guid("50000000-0000-0000-0000-000000000015"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedBy = "",
                            DriveId = new Guid("20000000-0000-0000-0000-000000000001"),
                            EncryptedCode = "C197AE0B65249730AEEA0EE9B68CE20BD53227E2360F78876CBF6D7D2CF5EED5",
                            IsDeleted = false,
                            IsRead = false,
                            MaskedCode = "AWS-****T6",
                            ModifiedBy = "",
                            Status = "Available",
                            TokenizedLink = "",
                            Value = 15000m,
                            Vendor = "AWS"
                        },
                        new
                        {
                            VoucherId = new Guid("50000000-0000-0000-0000-000000000016"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedBy = "",
                            DriveId = new Guid("20000000-0000-0000-0000-000000000001"),
                            EncryptedCode = "B7A8903BE01EEF165A788F95EA643D24A5423705CB77A443B8C9B11ACA7076DB",
                            IsDeleted = false,
                            IsRead = false,
                            MaskedCode = "AWS-****W2",
                            ModifiedBy = "",
                            Status = "Available",
                            TokenizedLink = "",
                            Value = 15000m,
                            Vendor = "AWS"
                        },
                        new
                        {
                            VoucherId = new Guid("50000000-0000-0000-0000-000000000017"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedBy = "",
                            DriveId = new Guid("20000000-0000-0000-0000-000000000001"),
                            EncryptedCode = "AE25CB29E3EAD141F2B16F67A4FCB13CF7249D55D596CA8FFB62F45872A2EE39",
                            IsDeleted = false,
                            IsRead = false,
                            MaskedCode = "AWS-****Z7",
                            ModifiedBy = "",
                            Status = "Available",
                            TokenizedLink = "",
                            Value = 15000m,
                            Vendor = "AWS"
                        },
                        new
                        {
                            VoucherId = new Guid("50000000-0000-0000-0000-000000000018"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedBy = "",
                            DriveId = new Guid("20000000-0000-0000-0000-000000000001"),
                            EncryptedCode = "3C075308CCCA78007FB6CD59C40774AC2D8798525483CD444A59BFA40679BEBF",
                            IsDeleted = false,
                            IsRead = false,
                            MaskedCode = "AWS-****C6",
                            ModifiedBy = "",
                            Status = "Available",
                            TokenizedLink = "",
                            Value = 15000m,
                            Vendor = "AWS"
                        },
                        new
                        {
                            VoucherId = new Guid("50000000-0000-0000-0000-000000000019"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedBy = "",
                            DriveId = new Guid("20000000-0000-0000-0000-000000000001"),
                            EncryptedCode = "CA799445714919C5CD3AA2470AB964291C94CC6D9899F86397620B4C55F8222A",
                            IsDeleted = false,
                            IsRead = false,
                            MaskedCode = "AWS-****F8",
                            ModifiedBy = "",
                            Status = "Available",
                            TokenizedLink = "",
                            Value = 15000m,
                            Vendor = "AWS"
                        },
                        new
                        {
                            VoucherId = new Guid("50000000-0000-0000-0000-000000000020"),
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedBy = "",
                            DriveId = new Guid("20000000-0000-0000-0000-000000000001"),
                            EncryptedCode = "39D9C4D32BCA74CC7F48C6703D6652BC4F1CDBD04035AEA7C6CC3663A0F49B49",
                            IsDeleted = false,
                            IsRead = false,
                            MaskedCode = "AWS-****J5",
                            ModifiedBy = "",
                            Status = "Available",
                            TokenizedLink = "",
                            Value = 15000m,
                            Vendor = "AWS"
                        });
                });

            modelBuilder.Entity("CertificationHub.Domain.Entities.AssessmentResult", b =>
                {
                    b.HasOne("CertificationHub.Domain.Entities.Registration", "Registration")
                        .WithOne("AssessmentResult")
                        .HasForeignKey("CertificationHub.Domain.Entities.AssessmentResult", "RegistrationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("CertificationHub.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("CertificationHub.Domain.Entities.CertificationDrive", "Drive")
                        .WithMany("AuditLogs")
                        .HasForeignKey("DriveId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Drive");
                });

            modelBuilder.Entity("CertificationHub.Domain.Entities.EligibilityRecord", b =>
                {
                    b.HasOne("CertificationHub.Domain.Entities.Registration", "Registration")
                        .WithOne("EligibilityRecord")
                        .HasForeignKey("CertificationHub.Domain.Entities.EligibilityRecord", "RegistrationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("CertificationHub.Domain.Entities.EmployeeCertification", b =>
                {
                    b.HasOne("CertificationHub.Domain.Entities.User", "User")
                        .WithMany("EmployeeCertifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CertificationHub.Domain.Entities.Notification", b =>
                {
                    b.HasOne("CertificationHub.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CertificationHub.Domain.Entities.Registration", b =>
                {
                    b.HasOne("CertificationHub.Domain.Entities.CertificationDrive", "Drive")
                        .WithMany("Registrations")
                        .HasForeignKey("DriveId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CertificationHub.Domain.Entities.User", "User")
                        .WithMany("Registrations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Drive");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CertificationHub.Domain.Entities.Voucher", b =>
                {
                    b.HasOne("CertificationHub.Domain.Entities.User", "AssignedToUser")
                        .WithMany("Vouchers")
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CertificationHub.Domain.Entities.CertificationDrive", "Drive")
                        .WithMany("Vouchers")
                        .HasForeignKey("DriveId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CertificationHub.Domain.Entities.Registration", null)
                        .WithOne("VoucherAllocation")
                        .HasForeignKey("CertificationHub.Domain.Entities.Voucher", "RegistrationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedToUser");

                    b.Navigation("Drive");
                });

            modelBuilder.Entity("CertificationHub.Domain.Entities.CertificationDrive", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Registrations");

                    b.Navigation("Vouchers");
                });

            modelBuilder.Entity("CertificationHub.Domain.Entities.Registration", b =>
                {
                    b.Navigation("AssessmentResult");

                    b.Navigation("EligibilityRecord");

                    b.Navigation("VoucherAllocation");
                });

            modelBuilder.Entity("CertificationHub.Domain.Entities.User", b =>
                {
                    b.Navigation("EmployeeCertifications");

                    b.Navigation("Notifications");

                    b.Navigation("Registrations");

                    b.Navigation("Vouchers");
                });
#pragma warning restore 612, 618
        }
    }
}
